In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### Sentences
sent = ["I love books",
         "i love cricket","today is saturday","i am a good guy","This is laptop"]

In [6]:
sent

['I love books',
 'i love cricket',
 'today is saturday',
 'i am a good guy',
 'This is laptop']

In [7]:
## vocublary size
voc_size = 10000

In [9]:
onehot_repr = [one_hot(words,voc_size) for words in sent]

In [10]:
onehot_repr

[[7088, 5894, 4717],
 [7088, 5894, 5075],
 [9711, 7387, 5830],
 [7088, 9218, 8432, 7974, 7755],
 [2081, 7387, 1050]]

### Word Embedding Represntation

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length = 8
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0    0 7088 5894 4717]
 [   0    0    0    0    0 7088 5894 5075]
 [   0    0    0    0    0 9711 7387 5830]
 [   0    0    0 7088 9218 8432 7974 7755]
 [   0    0    0    0    0 2081 7387 1050]]


In [15]:
dim = 10

In [16]:
model = Sequential()
model.add(Embedding(voc_size,10,input_length = sent_length))
model.compile("adam","mse")

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.predict(embedded_docs)

array([[[-0.01259607, -0.01461872,  0.04108428, -0.01538116,
         -0.03207218,  0.02368272,  0.0218176 ,  0.01356224,
          0.03621444, -0.00423534],
        [-0.01259607, -0.01461872,  0.04108428, -0.01538116,
         -0.03207218,  0.02368272,  0.0218176 ,  0.01356224,
          0.03621444, -0.00423534],
        [-0.01259607, -0.01461872,  0.04108428, -0.01538116,
         -0.03207218,  0.02368272,  0.0218176 ,  0.01356224,
          0.03621444, -0.00423534],
        [-0.01259607, -0.01461872,  0.04108428, -0.01538116,
         -0.03207218,  0.02368272,  0.0218176 ,  0.01356224,
          0.03621444, -0.00423534],
        [-0.01259607, -0.01461872,  0.04108428, -0.01538116,
         -0.03207218,  0.02368272,  0.0218176 ,  0.01356224,
          0.03621444, -0.00423534],
        [ 0.03758308, -0.0101737 ,  0.04437435, -0.01296037,
          0.00223767, -0.03924551,  0.00297906, -0.04256801,
         -0.01592542,  0.04836327],
        [-0.00906084,  0.00946157, -0.01854547,  0.0

In [20]:
model.predict(embedded_docs)[0]

array([[-0.01259607, -0.01461872,  0.04108428, -0.01538116, -0.03207218,
         0.02368272,  0.0218176 ,  0.01356224,  0.03621444, -0.00423534],
       [-0.01259607, -0.01461872,  0.04108428, -0.01538116, -0.03207218,
         0.02368272,  0.0218176 ,  0.01356224,  0.03621444, -0.00423534],
       [-0.01259607, -0.01461872,  0.04108428, -0.01538116, -0.03207218,
         0.02368272,  0.0218176 ,  0.01356224,  0.03621444, -0.00423534],
       [-0.01259607, -0.01461872,  0.04108428, -0.01538116, -0.03207218,
         0.02368272,  0.0218176 ,  0.01356224,  0.03621444, -0.00423534],
       [-0.01259607, -0.01461872,  0.04108428, -0.01538116, -0.03207218,
         0.02368272,  0.0218176 ,  0.01356224,  0.03621444, -0.00423534],
       [ 0.03758308, -0.0101737 ,  0.04437435, -0.01296037,  0.00223767,
        -0.03924551,  0.00297906, -0.04256801, -0.01592542,  0.04836327],
       [-0.00906084,  0.00946157, -0.01854547,  0.03679332,  0.04496494,
        -0.01697367, -0.0267287 ,  0.04534638